### ISSUE TITLE
Glance of call from Blocked Contacts!

### ISSUE THREAD

**Issue by brittle123** [eaglx/CallBlocker#3]
Hello Sir! The app is working perfectly fine when it's open but when i close the app it doesn't work then. Have you implemented the background service functionality in it or not?

**Comment by eaglx** [comment]
Hi @brittle123, 
could you provide more details about your Android version? 
The background service is implemented. Have you checked if an example unwanted call is blocked?

**Comment by brittle123** [comment]
Sorry!,.. it's working now,... for the first time it doesn't work for me,.. but when i again run this app it works,.. but in this there is one issue,... when i block any contact ,.. i'm having a glance of call from that blocked contact,... how to solve this?,.. In truecaller app we can't get any glance on the ringing state.

**Comment by brittle123** [comment]
my android version is 9 by the way and the device is Google pixel 1

**Comment by eaglx** [comment]
Thanks for information about this issue. I will try to reproduce it and fix.

**Comment by brittle123** [comment]
Will wait for it. Thanks.
