### ISSUE TITLE
Can't Block Call in this Android Version Error!

### ISSUE THREAD

**Issue by brittle123** [eaglx/CallBlocker#4]
Hello eaglx!,... when i run your demo app in my device(HTC m9) android version 6 it's working fine and blocking my blacklist calls but when i use your code in my app it's showing me the toast that "Can't block call in this android version" and showing me the notification of call blocked from that person but receiving call from him aswel. Please help me out of this ASAP!
Thanks & Regards.

**Comment by eaglx** [comment]
Hi,
sorry to hear that. But if the problem is **in your app**, I can't help you.
Regards, eaglX

**Comment by brittle123** [comment]
ok can you please tell me that how can we block users not using sqlite database but in phpmyadmin database?

**Comment by eaglx** [comment]
@brittle123 check here [stackoverflow.com how-to-import-com-android-internal-telephony-itelephony-to-the-android-applicati](https://stackoverflow.com/questions/24580508/how-to-import-com-android-internal-telephony-itelephony-to-the-android-applicati)
